## 1번 예제

In [1]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences #단어를 쪼갠 후 사이즈를 동일하게 맞춰주기 위해 빈자리에 0을 추가
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding #Embedding은 백터화 해주는 방식이다. 


#주어진 문장을 '단어'로 토큰화 하기

#케라스의 텍스트 전처리와 관련한 함수중 text_to_word_sequence 함수를 불러 옵니다.
from tensorflow.keras.preprocessing.text import text_to_word_sequence
 
# 전처리할 텍스트를 정합니다.
text = '해보지 않으면 해낼 수 없다'
 

In [2]:
# 해당 텍스트를 토큰화 합니다.
result = text_to_word_sequence(text)
print("\n원문:\n", text)
print("\n토큰화:\n", result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [3]:
#단어 빈도수 세기

#전처리 하려는 세개의 문장을 정합니다.
 
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
       '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.',
       ]
 
# 토큰화 함수를 이용해 전처리 하는 과정입니다.
token = Tokenizer()             # 토큰화 함수 지정

In [4]:
token.fit_on_texts(docs) 

In [6]:
#단어의 빈도수를 계산한 결과를 각 옵션에 맞추어 출력합니다. 
 
print("\n단어 카운트:\n", token.word_counts) 
#Tokenizer()의 word_counts 함수는 순서를 기억하는 OrderedDict클래스를 사용합니다.

#입력한 단어를 띄어쓰기를 기준으로 나눠준다. 
#그리고 각각이 몇번 나왔는지 알려준다. 


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용', 1), ('할', 1), ('수', 1), ('있습니다', 1)])


In [7]:
 #출력되는 순서는 랜덤입니다. 
print("\n문장 카운트: ", token.document_count)


문장 카운트:  3


In [8]:
print("\n각 단어가 몇개의 문장에 포함되어 있는가:\n", token.word_docs)


각 단어가 몇개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'텍스트의': 2, '단어를': 1, '나누어': 1, '토큰화': 3, '합니다': 1, '먼저': 1, '각': 1, '딥러닝에서': 2, '인식됩니다': 1, '해야': 1, '단어로': 1, '수': 1, '결과는': 1, '있습니다': 1, '한': 1, '할': 1, '사용': 1})


> 이 문장에서는 '토큰화'라는 단어가 가장 중요하다는 것을 알 수 있다. (3번 나왔기 때문)

In [9]:
print("\n각 단어에 매겨진 인덱스 값:\n",  token.word_index)


각 단어에 매겨진 인덱스 값:
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용': 14, '할': 15, '수': 16, '있습니다': 17}


## 2번 예제

In [11]:
# 텍스트 리뷰 자료를 지정합니다.
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1,1,1,1,1,0,0,0,0,0])
#사실 이 dataset을 만드는게 가장 어렵고 시간이 많이 걸린다. 

In [12]:
# 토큰화 
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  x) #각각의 문장이 몇번 인덱스를 참고하여 만들 수 있는건지 print 해줌

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}

리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [13]:
# 패딩, 서로 다른 길이의 데이터를 4로 맞추어 줍니다.
padded_x = pad_sequences(x, 4)  #문장의 길이가 가장 긴 것(4)를 기준으로 한다. #들어가는 입력 사이즈를 맞춰준다. 
print("\n패딩 결과:\n", padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [14]:
#딥러닝 모델
print("\n딥러닝 모델 시작:")

#임베딩에 입력될 단어의 수를 지정합니다.
word_size = len(token.word_index) +1
 
#단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten()) #1차원으로 만든다. 
model.add(Dense(1, activation='sigmoid')) #긍정인지 부정인지 (0인지 1인지)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))


딥러닝 모델 시작:
Epoch 1/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6924 - accuracy: 0.6000
Epoch 2/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6903 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6883 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6862 - accuracy: 0.7000
Epoch 5/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6842 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6821 - accuracy: 0.7000
Epoch 7/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6801 - accuracy: 0.7000
Epoch 8/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6780 - accuracy: 0.7000
Epoch 9/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6760 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6739 - accuracy: 0.9000
Epoch 11/20
1/1 [==========