In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

In [2]:
xdata = [[1,3],[2,2],[3,1],[4,6],[5,5],[6,4]] #공부한 시간, 출석일수
ydata = [[0],[0],[0],[1],[1],[1]] #0:불합격, 1:합격

In [3]:
x = tf.placeholder(tf.float32,shape=[None,2])
y = tf.constant(ydata, tf.float32)

In [4]:
w = tf.Variable(tf.random_uniform([2,1]))
b = tf.Variable(tf.random_uniform([1]))

In [5]:
z = tf.matmul(x,w) + b
hx = tf.nn.sigmoid(z) 

In [6]:
cost_i = y*(-tf.log(hx))+(1-y)*(-tf.log(1-hx))
cost = tf.reduce_mean(cost_i)

In [7]:
optimizer = tf.train.AdamOptimizer(0.01) #learning rate
train = optimizer.minimize(cost)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [8]:
for i in range(1000):
    sess.run(train, {x:xdata})
    print(i, sess.run(cost, {x:xdata}))

0 2.1930933
1 2.168415
2 2.1437542
3 2.1191137
4 2.0944898
5 2.0698867
6 2.0453076
7 2.0207512
8 1.9962201
9 1.9717169
10 1.9472399
11 1.9227929
12 1.8983809
13 1.8740005
14 1.8496556
15 1.8253497
16 1.801084
17 1.776862
18 1.7526845
19 1.7285553
20 1.704476
21 1.6804523
22 1.6564835
23 1.6325759
24 1.6087309
25 1.5849534
26 1.5612463
27 1.5376139
28 1.5140601
29 1.4905893
30 1.4672068
31 1.4439169
32 1.420724
33 1.3976349
34 1.3746532
35 1.351786
36 1.3290393
37 1.3064197
38 1.2839333
39 1.261588
40 1.2393904
41 1.2173496
42 1.1954725
43 1.1737686
44 1.1522467
45 1.1309162
46 1.1097878
47 1.088871
48 1.0681776
49 1.0477183
50 1.0275061
51 1.007553
52 0.98787206
53 0.9684775
54 0.9493835
55 0.9306045
56 0.912157
57 0.89405584
58 0.87631863
59 0.8589618
60 0.8420031
61 0.8254606
62 0.80935246
63 0.79369694
64 0.77851266
65 0.76381797
66 0.7496311
67 0.73596984
68 0.7228513
69 0.71029145
70 0.6983053
71 0.68690634
72 0.676106
73 0.6659137
74 0.6563365
75 0.64737827
76 0.6390402
77 0.6313

663 0.21598704
664 0.21561874
665 0.21525122
666 0.21488446
667 0.21451855
668 0.21415341
669 0.21378903
670 0.21342546
671 0.21306266
672 0.21270066
673 0.21233942
674 0.21197896
675 0.21161926
676 0.21126036
677 0.21090221
678 0.21054482
679 0.21018822
680 0.20983244
681 0.20947735
682 0.20912308
683 0.20876954
684 0.20841675
685 0.20806478
686 0.2077135
687 0.20736296
688 0.20701325
689 0.20666426
690 0.20631604
691 0.20596848
692 0.20562173
693 0.20527573
694 0.2049305
695 0.20458597
696 0.20424221
697 0.20389919
698 0.20355685
699 0.20321536
700 0.20287453
701 0.20253445
702 0.20219505
703 0.20185639
704 0.20151852
705 0.20118129
706 0.20084488
707 0.20050915
708 0.20017417
709 0.19983985
710 0.19950624
711 0.19917345
712 0.19884129
713 0.19850989
714 0.19817919
715 0.19784917
716 0.19751984
717 0.19719125
718 0.1968634
719 0.1965362
720 0.19620979
721 0.19588399
722 0.19555889
723 0.19523452
724 0.19491084
725 0.19458789
726 0.19426559
727 0.19394396
728 0.19362305
729 0.19330281

In [9]:
sess.run(w)

array([[0.69902986],
       [0.6989763 ]], dtype=float32)

In [10]:
sess.run(b)

array([-4.4080415], dtype=float32)

In [11]:
result = sess.run(hx,{x:[[3,5]]})

In [12]:
result>0.5

array([[ True]])

In [13]:
t = tf.cast(result>0.5, dtype=tf.int32) #cast함수: true인 경우에는 1로, false인 경우에는 0으로 바꿔주는 함수
sess.run(t)

array([[1]])

In [14]:
h = sess.run(hx, {x:xdata})

In [15]:
ydata

[[0], [0], [0], [1], [1], [1]]

In [16]:
h>0.5 #element wise 하게 계산된다. 

array([[False],
       [False],
       [False],
       [ True],
       [ True],
       [ True]])

In [17]:
((h>0.5) ==ydata).mean() #정확도가 100%이다. nd.array객체 멤버함수인 mean을 하면 정확도가 나온다. mean이 1이면 정확도가 100%이다. 

1.0

In [20]:
h

array([[0.16629966],
       [0.16630709],
       [0.1663145 ],
       [0.92968994],
       [0.9296934 ],
       [0.9296969 ]], dtype=float32)

In [26]:
predict = tf.cast(h>0.5, dtype=tf.float32) 
e = tf.equal(predict,y) #예측값과 실제 값이 모두 같은가? predict == y
m = tf.reduce_mean(tf.cast(e, dtype=tf.float32))
#sess.run(e) 
sess.run(m)

1.0

In [29]:
for i in range(10000):
    sess.run(train, {x:xdata}) #x가 placeholder 이기 때문에 값을 지정해줘야 한다,
    print(i, sess.run(cost, {x:xdata}))

0 0.12721251
1 0.12703006
2 0.12684804
3 0.12666635
4 0.126485
5 0.126304
6 0.12612335
7 0.12594308
8 0.12576318
9 0.1255836
10 0.12540437
11 0.1252255
12 0.12504701
13 0.12486884
14 0.12469102
15 0.124513544
16 0.12433642
17 0.12415961
18 0.1239832
19 0.123807095
20 0.12363136
21 0.12345594
22 0.123280875
23 0.12310615
24 0.122931786
25 0.12275773
26 0.12258405
27 0.12241068
28 0.12223766
29 0.12206494
30 0.12189261
31 0.12172056
32 0.1215489
33 0.121377565
34 0.121206515
35 0.121035844
36 0.12086549
37 0.12069547
38 0.120525755
39 0.12035642
40 0.12018734
41 0.12001864
42 0.11985025
43 0.119682185
44 0.11951443
45 0.11934704
46 0.11917993
47 0.11901317
48 0.11884669
49 0.11868057
50 0.118514754
51 0.118349284
52 0.11818412
53 0.11801926
54 0.11785474
55 0.117690496
56 0.11752658
57 0.117363036
58 0.11719974
59 0.11703676
60 0.11687412
61 0.11671177
62 0.11654975
63 0.116388015
64 0.11622659
65 0.11606553
66 0.1159047
67 0.11574423
68 0.115584046
69 0.11542421
70 0.115264624
71 0.1151

655 0.057055045
656 0.05699511
657 0.05693528
658 0.056875553
659 0.056815837
660 0.056756288
661 0.05669679
662 0.056637358
663 0.05657805
664 0.056518834
665 0.056459665
666 0.0564006
667 0.056341615
668 0.056282703
669 0.0562239
670 0.056165185
671 0.056106556
672 0.056047987
673 0.055989515
674 0.05593114
675 0.055872846
676 0.055814624
677 0.05575647
678 0.05569844
679 0.055640474
680 0.05558257
681 0.055524778
682 0.055467088
683 0.05540943
684 0.055351898
685 0.055294406
686 0.05523701
687 0.055179704
688 0.055122506
689 0.055065352
690 0.055008274
691 0.054951325
692 0.05489443
693 0.0548376
694 0.05478087
695 0.054724198
696 0.054667663
697 0.054611176
698 0.054554764
699 0.05449843
700 0.054442197
701 0.054386023
702 0.054329928
703 0.054273915
704 0.054217976
705 0.054162133
706 0.054106373
707 0.0540507
708 0.05399506
709 0.053939532
710 0.053884093
711 0.053828716
712 0.05377339
713 0.053718183
714 0.05366303
715 0.053608
716 0.053553015
717 0.05349809
718 0.053443268
719 

1389 0.028927764
1390 0.02890391
1391 0.028880132
1392 0.028856328
1393 0.0288326
1394 0.028808886
1395 0.028785184
1396 0.028761504
1397 0.028737864
1398 0.028714215
1399 0.028690616
1400 0.02866705
1401 0.028643519
1402 0.028619973
1403 0.028596481
1404 0.028573021
1405 0.028549572
1406 0.028526133
1407 0.028502747
1408 0.028479377
1409 0.028456045
1410 0.028432729
1411 0.028409451
1412 0.02838616
1413 0.02836292
1414 0.028339691
1415 0.028316515
1416 0.028293349
1417 0.028270205
1418 0.028247094
1419 0.028223984
1420 0.028200923
1421 0.028177882
1422 0.028154852
1423 0.028131885
1424 0.028108902
1425 0.02808596
1426 0.028063042
1427 0.02804015
1428 0.028017282
1429 0.02799444
1430 0.027971616
1431 0.02794881
1432 0.027926063
1433 0.027903318
1434 0.027880585
1435 0.027857905
1436 0.027835222
1437 0.027812572
1438 0.027789956
1439 0.027767345
1440 0.027744772
1441 0.027722219
1442 0.027699692
1443 0.027677193
1444 0.027654702
1445 0.027632272
1446 0.027609833
1447 0.027587412
1448 0.

2139 0.016410703
2140 0.01639924
2141 0.01638778
2142 0.016376315
2143 0.016364872
2144 0.01635343
2145 0.01634202
2146 0.016330587
2147 0.016319206
2148 0.016307818
2149 0.016296433
2150 0.016285066
2151 0.016273715
2152 0.016262354
2153 0.016251016
2154 0.016239686
2155 0.016228369
2156 0.016217029
2157 0.016205741
2158 0.016194442
2159 0.016183184
2160 0.016171908
2161 0.01616062
2162 0.016149374
2163 0.016138125
2164 0.016126892
2165 0.016115693
2166 0.01610447
2167 0.016093252
2168 0.016082065
2169 0.016070882
2170 0.016059717
2171 0.016048541
2172 0.016037418
2173 0.016026264
2174 0.016015118
2175 0.016003976
2176 0.015992852
2177 0.01598175
2178 0.015970657
2179 0.015959563
2180 0.015948512
2181 0.01593742
2182 0.015926369
2183 0.015915316
2184 0.015904274
2185 0.015893264
2186 0.015882242
2187 0.015871232
2188 0.015860222
2189 0.015849233
2190 0.015838264
2191 0.015827285
2192 0.015816314
2193 0.015805375
2194 0.015794417
2195 0.015783498
2196 0.01577255
2197 0.01576163
2198 0.

2894 0.009973214
2895 0.009966952
2896 0.009960711
2897 0.0099545
2898 0.009948258
2899 0.009942028
2900 0.0099358065
2901 0.0099295955
2902 0.009923375
2903 0.009917195
2904 0.0099110035
2905 0.009904783
2906 0.0098985825
2907 0.009892422
2908 0.009886252
2909 0.009880042
2910 0.0098738605
2911 0.009867721
2912 0.009861551
2913 0.00985538
2914 0.009849221
2915 0.009843111
2916 0.009836901
2917 0.009830791
2918 0.009824662
2919 0.009818532
2920 0.009812391
2921 0.009806283
2922 0.009800153
2923 0.009794064
2924 0.009787935
2925 0.009781855
2926 0.009775726
2927 0.009769616
2928 0.009763557
2929 0.009757458
2930 0.00975135
2931 0.009745301
2932 0.009739253
2933 0.009733153
2934 0.009727084
2935 0.009721026
2936 0.009714968
2937 0.009708939
2938 0.009702911
2939 0.009696842
2940 0.009690814
2941 0.0096847955
2942 0.009678747
2943 0.00967274
2944 0.009666712
2945 0.009660694
2946 0.009654676
2947 0.009648678
2948 0.00964266
2949 0.0096366415
2950 0.0096306745
2951 0.009624707
2952 0.00961

3653 0.006316367
3654 0.0063126646
3655 0.0063089817
3656 0.006305329
3657 0.006301696
3658 0.0062980535
3659 0.006294331
3660 0.0062906886
3661 0.006287066
3662 0.006283413
3663 0.0062797703
3664 0.0062761474
3665 0.0062725153
3666 0.0062688123
3667 0.00626518
3668 0.0062615573
3669 0.006257925
3670 0.0062542926
3671 0.0062506604
3672 0.006247058
3673 0.0062434357
3674 0.006239813
3675 0.0062361904
3676 0.006232588
3677 0.0062289755
3678 0.0062253433
3679 0.0062217508
3680 0.0062181386
3681 0.0062145162
3682 0.0062109143
3683 0.006207332
3684 0.00620372
3685 0.006200167
3686 0.0061965645
3687 0.006192982
3688 0.0061893812
3689 0.006185778
3690 0.0061821756
3691 0.0061786734
3692 0.006175082
3693 0.00617148
3694 0.006167888
3695 0.006164326
3696 0.006160794
3697 0.0061572012
3698 0.00615363
3699 0.006150108
3700 0.006146546
3701 0.006142964
3702 0.0061394013
3703 0.00613589
3704 0.006132308
3705 0.0061287363
3706 0.006125254
3707 0.006121682
3708 0.00611815
3709 0.0061145984
3710 0.006

4410 0.004116736
4411 0.0041144597
4412 0.004112204
4413 0.004109938
4414 0.004107662
4415 0.004105407
4416 0.004103131
4417 0.0041008648
4418 0.004098599
4419 0.004096343
4420 0.0040940773
4421 0.0040918314
4422 0.0040895655
4423 0.0040873294
4424 0.004085064
4425 0.004082808
4426 0.004080542
4427 0.004078297
4428 0.0040760506
4429 0.004073785
4430 0.004071549
4431 0.004069323
4432 0.004067067
4433 0.004064821
4434 0.004062606
4435 0.0040603396
4436 0.004058094
4437 0.004055858
4438 0.0040536327
4439 0.0040513766
4440 0.004049181
4441 0.0040469454
4442 0.0040447293
4443 0.0040424834
4444 0.004040248
4445 0.004038032
4446 0.0040357965
4447 0.00403355
4448 0.004031335
4449 0.004029149
4450 0.004026933
4451 0.0040247175
4452 0.0040224916
4453 0.004020266
4454 0.00401805
4455 0.0040158345
4456 0.004013639
4457 0.0040114233
4458 0.0040092077
4459 0.004007022
4460 0.0040048063
4461 0.00400259
4462 0.0040003746
4463 0.0039981892
4464 0.0039959927
4465 0.0039937776
4466 0.003991592
4467 0.003

5168 0.002729713
5169 0.002728238
5170 0.0027268028
5171 0.0027253581
5172 0.0027239027
5173 0.0027224282
5174 0.0027209732
5175 0.0027195383
5176 0.0027181327
5177 0.002716678
5178 0.0027152228
5179 0.002713768
5180 0.0027123329
5181 0.0027108977
5182 0.0027094625
5183 0.002707988
5184 0.002706533
5185 0.002705098
5186 0.002703663
5187 0.0027022278
5188 0.0027007728
5189 0.0026993176
5190 0.0026978634
5191 0.0026964378
5192 0.002695023
5193 0.002693588
5194 0.0026921527
5195 0.0026906978
5196 0.0026892729
5197 0.0026878277
5198 0.0026864226
5199 0.0026850076
5200 0.0026835725
5201 0.0026821375
5202 0.0026807326
5203 0.0026792977
5204 0.0026778725
5205 0.0026764178
5206 0.0026750125
5207 0.0026735775
5208 0.0026721528
5209 0.0026707174
5210 0.0026693128
5211 0.0026678776
5212 0.0026664725
5213 0.0026650375
5214 0.0026636322
5215 0.0026621977
5216 0.0026607923
5217 0.0026593872
5218 0.0026579623
5219 0.0026565474
5220 0.002655172
5221 0.0026537671
5222 0.0026523422
5223 0.0026509073
522

5932 0.0018256953
5933 0.0018247198
5934 0.0018238039
5935 0.0018228282
5936 0.0018218826
5937 0.0018209368
5938 0.001820021
5939 0.0018190751
5940 0.0018181094
5941 0.0018171836
5942 0.0018162378
5943 0.0018152822
5944 0.0018143564
5945 0.0018133906
5946 0.0018124449
5947 0.0018115094
5948 0.0018105634
5949 0.0018096175
5950 0.0018086721
5951 0.0018077361
5952 0.0018068003
5953 0.0018058548
5954 0.0018049189
5955 0.0018039834
5956 0.0018030374
5957 0.0018021016
5958 0.0018011658
5959 0.0018002201
5960 0.0017992841
5961 0.0017983489
5962 0.0017974129
5963 0.0017964769
5964 0.0017955414
5965 0.0017946254
5966 0.0017936699
5967 0.001792734
5968 0.0017918181
5969 0.0017908924
5970 0.0017899368
5971 0.0017890207
5972 0.0017880852
5973 0.0017871592
5974 0.0017862236
5975 0.0017852877
5976 0.0017843818
5977 0.0017834463
5978 0.0017825005
5979 0.0017815843
5980 0.001780659
5981 0.0017797529
5982 0.0017787976
5983 0.0017778715
5984 0.0017769655
5985 0.0017760299
5986 0.001775124
5987 0.0017741

6685 0.0012377987
6686 0.001237152
6687 0.0012365055
6688 0.0012358787
6689 0.0012352518
6690 0.0012346052
6691 0.0012339883
6692 0.0012333717
6693 0.001232725
6694 0.0012321082
6695 0.0012314615
6696 0.0012308346
6697 0.0012302081
6698 0.0012295613
6699 0.0012289445
6700 0.0012283177
6701 0.001227691
6702 0.0012270644
6703 0.0012264176
6704 0.0012257909
6705 0.0012251742
6706 0.0012245375
6707 0.0012239207
6708 0.001223294
6709 0.0012226672
6710 0.0012220304
6711 0.0012214138
6712 0.001220777
6713 0.0012201503
6714 0.0012195335
6715 0.0012189265
6716 0.00121828
6717 0.0012176632
6718 0.0012170564
6719 0.0012164296
6720 0.001215783
6721 0.0012151762
6722 0.0012145394
6723 0.0012139227
6724 0.0012133158
6725 0.0012126891
6726 0.0012120524
6727 0.0012114455
6728 0.0012108189
6729 0.0012102119
6730 0.0012095952
6731 0.0012089586
6732 0.0012083518
6733 0.001207725
6734 0.0012071083
6735 0.0012064815
6736 0.0012058747
6737 0.001205258
6738 0.001204651
6739 0.0012040343
6740 0.0012033975
674

7442 0.00084190164
7443 0.0008414841
7444 0.00084106624
7445 0.00084063876
7446 0.0008402013
7447 0.0008397836
7448 0.00083934603
7449 0.0008389284
7450 0.00083848106
7451 0.0008380632
7452 0.00083764567
7453 0.000837228
7454 0.0008368105
7455 0.0008363728
7456 0.0008359552
7457 0.0008355177
7458 0.0008351
7459 0.0008346823
7460 0.00083424494
7461 0.0008338273
7462 0.0008334196
7463 0.00083300186
7464 0.0008325843
7465 0.0008321468
7466 0.0008317291
7467 0.00083132135
7468 0.0008308839
7469 0.00083046634
7470 0.0008300585
7471 0.000829621
7472 0.00082920346
7473 0.0008287858
7474 0.00082836807
7475 0.0008279504
7476 0.00082752295
7477 0.00082710525
7478 0.00082669756
7479 0.0008262799
7480 0.00082585245
7481 0.00082543475
7482 0.00082501705
7483 0.00082457956
7484 0.000824172
7485 0.0008237542
7486 0.0008233465
7487 0.0008229389
7488 0.0008225213
7489 0.0008221035
7490 0.00082167605
7491 0.00082126836
7492 0.00082086073
7493 0.000820443
7494 0.00082000555
7495 0.00081959786
7496 0.0008

8196 0.0005755766
8197 0.0005752884
8198 0.0005749802
8199 0.00057470193
8200 0.00057442347
8201 0.00057412527
8202 0.00057385693
8203 0.00057352893
8204 0.0005732604
8205 0.0005729722
8206 0.0005726938
8207 0.0005724055
8208 0.0005720973
8209 0.0005718389
8210 0.0005715208
8211 0.0005712624
8212 0.00057095423
8213 0.0005706659
8214 0.00057038764
8215 0.0005700994
8216 0.0005698309
8217 0.0005695227
8218 0.0005692444
8219 0.0005689562
8220 0.0005686678
8221 0.00056837953
8222 0.00056808133
8223 0.00056783285
8224 0.00056752464
8225 0.0005672364
8226 0.00056695804
8227 0.0005666698
8228 0.00056640134
8229 0.0005660932
8230 0.00056582486
8231 0.0005655465
8232 0.0005652383
8233 0.0005649898
8234 0.0005646717
8235 0.0005644033
8236 0.0005641051
8237 0.00056383666
8238 0.0005635484
8239 0.0005632502
8240 0.00056300167
8241 0.0005626935
8242 0.00056241517
8243 0.0005621368
8244 0.0005618387
8245 0.00056157017
8246 0.0005612819
8247 0.00056100363
8248 0.0005607154
8249 0.000560427
8250 0.000

8932 0.0003980229
8933 0.00039782413
8934 0.00039761545
8935 0.00039742663
8936 0.00039721793
8937 0.00039701912
8938 0.00039682034
8939 0.00039662156
8940 0.00039642278
8941 0.00039622397
8942 0.00039602525
8943 0.0003958265
8944 0.0003956277
8945 0.00039542894
8946 0.00039523016
8947 0.00039503133
8948 0.0003948326
8949 0.00039463383
8950 0.00039443505
8951 0.0003942363
8952 0.0003940574
8953 0.00039385862
8954 0.00039365984
8955 0.00039346106
8956 0.00039326225
8957 0.0003930834
8958 0.0003928846
8959 0.00039268585
8960 0.00039248707
8961 0.0003923082
8962 0.00039211937
8963 0.00039191064
8964 0.00039171186
8965 0.000391523
8966 0.00039132425
8967 0.00039112545
8968 0.0003909267
8969 0.00039072792
8970 0.0003905391
8971 0.00039034034
8972 0.0003901416
8973 0.00038994275
8974 0.00038974397
8975 0.00038955515
8976 0.0003893564
8977 0.00038915765
8978 0.00038895887
8979 0.00038876012
8980 0.00038857126
8981 0.00038837246
8982 0.00038818363
8983 0.00038798482
8984 0.00038778607
8985 0.0

9690 0.0002726949
9691 0.00027253592
9692 0.00027244646
9693 0.0002722875
9694 0.00027212844
9695 0.000272039
9696 0.00027188
9697 0.00027173097
9698 0.00027163158
9699 0.00027147259
9700 0.00027132357
9701 0.00027122418
9702 0.00027107514
9703 0.0002709161
9704 0.00027079685
9705 0.00027066766
9706 0.00027050867
9707 0.00027039938
9708 0.0002702702
9709 0.00027011122
9710 0.00026999196
9711 0.0002698628
9712 0.0002697038
9713 0.00026959446
9714 0.00026946526
9715 0.00026930627
9716 0.00026918703
9717 0.00026905787
9718 0.00026889888
9719 0.00026878956
9720 0.0002686604
9721 0.00026850135
9722 0.00026840196
9723 0.00026825292
9724 0.00026810387
9725 0.00026800449
9726 0.00026785544
9727 0.00026769648
9728 0.000267607
9729 0.00026744805
9730 0.000267299
9731 0.00026720957
9732 0.0002670505
9733 0.00026690148
9734 0.000266812
9735 0.00026665305
9736 0.00026649405
9737 0.00026640462
9738 0.00026625558
9739 0.00026609655
9740 0.00026600712
9741 0.00026585805
9742 0.00026569908
9743 0.00026

In [30]:
sess.run(predict)

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [33]:
sess.run(m, {x:xdata})

1.0