In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt

In [2]:
#numpy에서는 #을 주석으로 읽기 때문에 pandas가 아니라 numpy로 읽어주겠다. 
arr = np.loadtxt('data/softmax.txt')
arr
# [,공부한 시간, 출석일수,001:C,010:B,100:A] 분류값을 바꾸는  것은 keras에 함수가 내장되어 있다. 

array([[1., 2., 1., 0., 0., 1.],
       [1., 3., 2., 0., 0., 1.],
       [1., 3., 4., 0., 0., 1.],
       [1., 5., 5., 0., 1., 0.],
       [1., 7., 5., 0., 1., 0.],
       [1., 2., 5., 0., 1., 0.],
       [1., 6., 6., 1., 0., 0.],
       [1., 7., 7., 1., 0., 0.]])

In [3]:
xdata = arr[:,1:3]
ydata = arr[:,3:]

In [4]:
xdata.shape

(8, 2)

In [5]:
ydata

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [6]:
x = tf.placeholder(tf.float32,[None,2])
y = tf.constant(ydata,tf.float32)

In [7]:
#원래 사비어 초기화 해줘야한다 
w = tf.Variable(tf. random_uniform([2,3])) #[feature개수, 분류의 개수]
b = tf.Variable(tf. random_uniform([3]))

In [8]:
z=tf.matmul(x,w)+b
hx = tf.nn.softmax(z) #뉴럴네트워크에 있는 소프트맥스를 통과한다. 확률값으로 나옴
cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits=z, labels=y)  #소프트맥스와 크로스앤트로피가 결합되어있는 것이다. 
#그래서 z값을 넣어주는 것이다. 사실 hx과정은 안해줘도 되는 것임. 

cost = tf.reduce_mean(cost_i)

In [9]:
optimizer = tf.train.GradientDescentOptimizer(0.1) #Learning rate
train = optimizer.minimize(cost)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [10]:
for i in range( 1000):  #최대한 돌려주고 earlystopping 돌리면 된다. 
    sess.run( train, {x:xdata})
    print( i, sess.run(cost, {x:xdata}))

0 1.2062533
1 1.0856061
2 1.0703646
3 1.06546
4 1.0606899
5 1.0560448
6 1.0515167
7 1.0470982
8 1.0427831
9 1.0385659
10 1.0344405
11 1.0304027
12 1.0264475
13 1.0225711
14 1.0187694
15 1.0150387
16 1.0113755
17 1.007777
18 1.00424
19 1.000762
20 0.99734014
21 0.99397236
22 0.99065626
23 0.9873898
24 0.98417103
25 0.9809983
26 0.9778698
27 0.9747841
28 0.9717394
29 0.9687347
30 0.96576846
31 0.96283966
32 0.95994693
33 0.9570894
34 0.95426595
35 0.9514756
36 0.9487176
37 0.9459907
38 0.94329464
39 0.9406284
40 0.93799114
41 0.93538237
42 0.9328013
43 0.9302475
44 0.9277202
45 0.9252188
46 0.922743
47 0.920292
48 0.9178657
49 0.91546315
50 0.91308427
51 0.91072845
52 0.90839535
53 0.9060844
54 0.9037955
55 0.90152824
56 0.89928186
57 0.8970567
58 0.8948518
59 0.8926672
60 0.89050233
61 0.88835716
62 0.8862311
63 0.8841243
64 0.882036
65 0.87996626
66 0.87791467
67 0.8758811
68 0.87386507
69 0.8718666
70 0.8698853
71 0.86792094
72 0.86597335
73 0.8640424
74 0.86212766
75 0.8602291
76 0.8

854 0.48645416
855 0.48628268
856 0.48611152
857 0.4859404
858 0.48576957
859 0.4855991
860 0.48542857
861 0.48525834
862 0.48508817
863 0.48491848
864 0.48474857
865 0.48457927
866 0.48440993
867 0.48424083
868 0.48407203
869 0.48390323
870 0.48373473
871 0.4835664
872 0.48339826
873 0.48323035
874 0.48306257
875 0.48289502
876 0.4827276
877 0.4825604
878 0.4823933
879 0.48222655
880 0.4820599
881 0.48189348
882 0.48172706
883 0.48156103
884 0.48139513
885 0.48122936
886 0.48106387
887 0.48089856
888 0.48073336
889 0.4805684
890 0.48040357
891 0.4802389
892 0.48007452
893 0.4799103
894 0.47974616
895 0.47958225
896 0.47941858
897 0.47925496
898 0.4790917
899 0.47892845
900 0.4787654
901 0.47860262
902 0.47844
903 0.47827747
904 0.47811508
905 0.47795302
906 0.47779104
907 0.4776293
908 0.47746775
909 0.47730634
910 0.47714502
911 0.4769839
912 0.47682306
913 0.47666225
914 0.47650176
915 0.47634137
916 0.4761812
917 0.47602114
918 0.47586125
919 0.47570157
920 0.47554195
921 0.4753826

In [11]:
sess.run(w)

array([[ 0.581692  ,  0.44120467,  0.29725415],
       [ 1.3469074 ,  0.74280375, -0.39858177]], dtype=float32)

In [12]:
sess.run(b)

array([-4.3109574 ,  0.01033567,  5.0209827 ], dtype=float32)

In [13]:
sess.run(hx,{x:[[6,6]]}) #소프트맥스 통과 후

array([[0.5203126 , 0.44951856, 0.03016879]], dtype=float32)

A학점을 받을 확률이 높다

In [14]:
sess.run(z,{x:[[6,6]]}) #소프트맥스 통과 전

array([[7.2606387, 7.114386 , 4.413017 ]], dtype=float32)

In [15]:
h = sess.run(hx,{x:[[6,6]]})
h.argmax(axis=1) #벡터값

array([0], dtype=int64)

In [22]:
grade = ['A', 'B', 'C']
grade[int(h.argmax(axis=1))]

'A'

In [28]:
#공부한 시간과 출석일수가 [6,6] [1,1] 인 경우
hh = sess.run(hx,{x:[[6,6],[1,1]]})
hh.argmax(axis=1)

array([0, 2], dtype=int64)

argmax

In [17]:
myarr = np.array([[1,2,3],[3,4,5]])
myarr

array([[1, 2, 3],
       [3, 4, 5]])

In [18]:
myarr.shape

(2, 3)

In [19]:
myarr.argmax()

5

In [20]:
myarr.argmax(axis=0) #열단위로 가장 큰 인자의 인덱스

array([1, 1, 1], dtype=int64)

In [21]:
myarr.argmax(axis=1) #행단위로 가장 큰 인자의 인덱스

array([2, 2], dtype=int64)