In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
from sklearn import datasets
from tensorflow.keras.backend import one_hot
import matplotlib.pyplot as plt

In [2]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
sess = tf.Session()

In [5]:
t= one_hot(iris['target'],3)
sess.run(t)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [6]:
arr = iris['data'] #sl 5.1, sw 3.5, pl 1.4, pw 0.2 종분류 및 정확도
arr

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
xdata = arr
ydata = t

In [8]:
x = tf.placeholder(tf.float32,[None,4])
y = ydata

w = tf.Variable(tf.random_uniform([4,3]))
b = tf.Variable(tf.random_uniform([3]))

z = tf.matmul(x,w) + b
hx = tf.nn.softmax(z)
cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits= z, labels=y) #logits 인자에는 hx함수 , labels= Tensor형 yvalue
cost = tf.reduce_mean(cost_i)

optimizer = tf.train.GradientDescentOptimizer(0.1) #learning rate
train = optimizer.minimize(cost)
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [9]:
hist_loss =[]
patience = 16
min_delta = 0.001 #이전값과 16번 비교하여 min_delta보다 작으면 빠져나가겠다. 
pcnt = 0

In [10]:
for i in range(30000):
    sess.run(train,{x:xdata}) #벼림 연산 # w = w.assign(w-0.1*g)
    c = sess.run(cost,{x:xdata}) 
    hist_loss.append( c )
    print(i, c)
    if i > 0 :
        if hist_loss[i-1]-hist_loss[i] > min_delta:
            pcnt = 0
        else:
            pcnt+= 1
        if pcnt > patience:
            print ('early stopping...')
            break

0 1.6131135
1 1.3918651
2 1.3050293
3 1.2006435
4 1.1328315
5 1.0581136
6 1.0068244
7 0.9583406
8 0.9183781
9 0.8951101
10 0.8594223
11 0.8572288
12 0.8199766
13 0.83310163
14 0.7914702
15 0.8150884
16 0.7686091
17 0.79950166
18 0.74904144
19 0.78520304
20 0.7319036
21 0.77202976
22 0.7167426
23 0.75991946
24 0.70319456
25 0.74874765
26 0.6909525
27 0.7383683
28 0.6797716
29 0.72864896
30 0.66945934
31 0.7194779
32 0.6598655
33 0.7107641
34 0.6508716
35 0.7024332
36 0.6423826
37 0.69442344
38 0.6343227
39 0.68668497
40 0.6266306
41 0.6791772
42 0.61925507
43 0.6718649
44 0.6121543
45 0.66471946
46 0.6052928
47 0.65771663
48 0.59864205
49 0.6508369
50 0.59217656
51 0.6440628
52 0.5858756
53 0.6373801
54 0.57972014
55 0.630776
56 0.57369477
57 0.6242395
58 0.56778586
59 0.6177623
60 0.561981
61 0.6113355
62 0.5562707
63 0.6049538
64 0.5506448
65 0.5986108
66 0.54509556
67 0.59230083
68 0.5396158
69 0.5860208
70 0.53419906
71 0.57976663
72 0.52883965
73 0.57353514
74 0.52353215
75 0.56732

# 확률값

In [11]:
h = sess.run(hx,{x:[[5.1,3.5,1.4,0.2]]}) #hx값을 구하려면 z값을 구해야하고, z값을 구하려면 x값이 필요하기 때문에 x를 넣어준다. 
h

array([[9.589498e-01, 4.099500e-02, 5.523289e-05]], dtype=float32)

# 종분류

In [12]:
feature_name = ['setosa','versicolor','virginica']
feature_name[int(h.argmax(axis = 1))] #row단위로 가장 큰 값을 구한다. 

'setosa'

In [22]:
h1 = sess.run(hx, {x:xdata})
h1

array([[9.58949804e-01, 4.09950390e-02, 5.52328893e-05],
       [9.22634542e-01, 7.71629214e-02, 2.02560434e-04],
       [9.46195841e-01, 5.36820479e-02, 1.22135549e-04],
       [9.15509045e-01, 8.41806158e-02, 3.10406671e-04],
       [9.63050365e-01, 3.68997306e-02, 4.97844558e-05],
       [9.57275808e-01, 4.26627472e-02, 6.13923839e-05],
       [9.47159469e-01, 5.26939668e-02, 1.46534061e-04],
       [9.44625854e-01, 5.52699491e-02, 1.04308754e-04],
       [9.05619144e-01, 9.39420164e-02, 4.38819872e-04],
       [9.23091829e-01, 7.67255425e-02, 1.82720061e-04],
       [9.64071631e-01, 3.58936563e-02, 3.46706802e-05],
       [9.32867944e-01, 6.69548362e-02, 1.77248512e-04],
       [9.24786508e-01, 7.50264972e-02, 1.86958307e-04],
       [9.49212790e-01, 5.06553203e-02, 1.31887457e-04],
       [9.85928297e-01, 1.40672615e-02, 4.48998753e-06],
       [9.84280944e-01, 1.57111771e-02, 7.87226691e-06],
       [9.77818727e-01, 2.21634973e-02, 1.77967722e-05],
       [9.57007170e-01, 4.29257

In [24]:
h2 = h1.argmax(axis = 1)
h2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

# 정확도

In [28]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(h2, iris['target']), dtype=tf.float32))

In [29]:
sess.run(accuracy,{x:xdata})

0.96666664