In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
from sklearn import datasets
# from tensorflow.keras.backend import one_hot #session run이 필요하다. 
from tensorflow.keras.utils import to_categorical #session이 필요 없기 때문에 이걸 쓰면 된다. 굳이 one-hot으로 변경 안해도 된다.
import matplotlib.pyplot as plt

In [2]:
iris = datasets.load_iris()
xdata = iris['data']
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
ydata = to_categorical(iris['target'],3) #one-hot할 필요 없음. 이게 ydata 이다. 

In [4]:
IO = Dense(units=3, input_dim=4, activation='softmax')  #units = 분류의 개수, input_dim = feature의 열의 개수
model = Sequential([IO])
model.compile(loss='categorical_crossentropy',optimizer=Adam(0.1),metrics=['accuracy'])
h = model.fit(xdata,ydata,epochs=1000)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Train on 150 samples
Epoch 1/1000
150/150 [==============================] - 0s 848us/sample - loss: 1.9520 - acc: 0.3000
Epoch 2/1000
150/150 [==============================] - 0s 85us/sample - loss: 1.5979 - acc: 0.3533
Epoch 3/1000
150/150 [==============================] - 0s 89us/sample - loss: 0.8273 - acc: 0.5467
Epoch 4/1000
150/150 [==============================] - 0s 87us/sample - loss: 0.7085 - acc: 0.6600
Epoch 5/1000
150/150 [==============================] - 0s 87us/sample - loss: 0.5491 - acc: 0.7800
Epoch 6/1000
150/150 [==============================] - 0s 99us/sample - loss: 0.5006 - acc: 0.7000
Epoch 7/1000
150/150 [==============================] - 0s 54us/sample - loss: 0.4416 - acc: 0.7800
Epoch 8/1000
150/150 [==============================] - 0s 75us/sample - loss: 0.3822 - acc: 0.8400
Epoch 9/1000
150/150 [==============================] - 0s 93us/sample - loss: 0.3695 - acc: 0.87

150/150 [==============================] - 0s 69us/sample - loss: 0.0993 - acc: 0.9733
Epoch 78/1000
150/150 [==============================] - 0s 89us/sample - loss: 0.0999 - acc: 0.9667
Epoch 79/1000
150/150 [==============================] - 0s 95us/sample - loss: 0.1012 - acc: 0.9733
Epoch 80/1000
150/150 [==============================] - 0s 99us/sample - loss: 0.0994 - acc: 0.9733
Epoch 81/1000
150/150 [==============================] - 0s 87us/sample - loss: 0.1010 - acc: 0.9733
Epoch 82/1000
150/150 [==============================] - 0s 105us/sample - loss: 0.1086 - acc: 0.9733
Epoch 83/1000
150/150 [==============================] - 0s 79us/sample - loss: 0.1188 - acc: 0.9733
Epoch 84/1000
150/150 [==============================] - 0s 95us/sample - loss: 0.1079 - acc: 0.9733
Epoch 85/1000
150/150 [==============================] - 0s 91us/sample - loss: 0.0945 - acc: 0.9733
Epoch 86/1000
150/150 [==============================] - 0s 88us/sample - loss: 0.0985 - acc: 0.9600
Epo

150/150 [==============================] - 0s 80us/sample - loss: 0.0711 - acc: 0.9733
Epoch 158/1000
150/150 [==============================] - 0s 82us/sample - loss: 0.0845 - acc: 0.9733
Epoch 159/1000
150/150 [==============================] - 0s 92us/sample - loss: 0.0680 - acc: 0.9867
Epoch 160/1000
150/150 [==============================] - 0s 79us/sample - loss: 0.0713 - acc: 0.9733
Epoch 161/1000
150/150 [==============================] - 0s 77us/sample - loss: 0.0675 - acc: 0.9800
Epoch 162/1000
150/150 [==============================] - 0s 96us/sample - loss: 0.0674 - acc: 0.9800
Epoch 163/1000
150/150 [==============================] - 0s 85us/sample - loss: 0.0685 - acc: 0.9800
Epoch 164/1000
150/150 [==============================] - 0s 64us/sample - loss: 0.0658 - acc: 0.9800
Epoch 165/1000
150/150 [==============================] - 0s 73us/sample - loss: 0.0690 - acc: 0.9733
Epoch 166/1000
150/150 [==============================] - 0s 86us/sample - loss: 0.0697 - acc: 0.

150/150 [==============================] - 0s 88us/sample - loss: 0.0582 - acc: 0.9800
Epoch 238/1000
150/150 [==============================] - 0s 73us/sample - loss: 0.0598 - acc: 0.9867
Epoch 239/1000
150/150 [==============================] - 0s 77us/sample - loss: 0.0604 - acc: 0.9800
Epoch 240/1000
150/150 [==============================] - 0s 72us/sample - loss: 0.0572 - acc: 0.9800
Epoch 241/1000
150/150 [==============================] - 0s 51us/sample - loss: 0.0616 - acc: 0.9867
Epoch 242/1000
150/150 [==============================] - 0s 61us/sample - loss: 0.0639 - acc: 0.9733
Epoch 243/1000
150/150 [==============================] - 0s 55us/sample - loss: 0.0657 - acc: 0.9733
Epoch 244/1000
150/150 [==============================] - 0s 77us/sample - loss: 0.0621 - acc: 0.9867
Epoch 245/1000
150/150 [==============================] - 0s 70us/sample - loss: 0.0652 - acc: 0.9800
Epoch 246/1000
150/150 [==============================] - 0s 60us/sample - loss: 0.0589 - acc: 0.

150/150 [==============================] - 0s 44us/sample - loss: 0.0549 - acc: 0.9800
Epoch 318/1000
150/150 [==============================] - 0s 83us/sample - loss: 0.0558 - acc: 0.9800
Epoch 319/1000
150/150 [==============================] - 0s 57us/sample - loss: 0.0569 - acc: 0.9867
Epoch 320/1000
150/150 [==============================] - 0s 82us/sample - loss: 0.0511 - acc: 0.9800
Epoch 321/1000
150/150 [==============================] - 0s 80us/sample - loss: 0.0552 - acc: 0.9800
Epoch 322/1000
150/150 [==============================] - 0s 78us/sample - loss: 0.0680 - acc: 0.9733
Epoch 323/1000
150/150 [==============================] - 0s 86us/sample - loss: 0.0664 - acc: 0.9667
Epoch 324/1000
150/150 [==============================] - 0s 80us/sample - loss: 0.0529 - acc: 0.9800
Epoch 325/1000
150/150 [==============================] - 0s 80us/sample - loss: 0.0583 - acc: 0.9733
Epoch 326/1000
150/150 [==============================] - 0s 65us/sample - loss: 0.0542 - acc: 0.

150/150 [==============================] - 0s 80us/sample - loss: 0.0530 - acc: 0.9800
Epoch 398/1000
150/150 [==============================] - 0s 95us/sample - loss: 0.0596 - acc: 0.9800
Epoch 399/1000
150/150 [==============================] - 0s 96us/sample - loss: 0.0557 - acc: 0.9800
Epoch 400/1000
150/150 [==============================] - 0s 87us/sample - loss: 0.0478 - acc: 0.9867
Epoch 401/1000
150/150 [==============================] - 0s 80us/sample - loss: 0.0571 - acc: 0.9800
Epoch 402/1000
150/150 [==============================] - 0s 56us/sample - loss: 0.0494 - acc: 0.9800
Epoch 403/1000
150/150 [==============================] - 0s 80us/sample - loss: 0.0520 - acc: 0.9733
Epoch 404/1000
150/150 [==============================] - 0s 66us/sample - loss: 0.0519 - acc: 0.9867
Epoch 405/1000
150/150 [==============================] - 0s 86us/sample - loss: 0.0531 - acc: 0.9800
Epoch 406/1000
150/150 [==============================] - 0s 62us/sample - loss: 0.0556 - acc: 0.

150/150 [==============================] - 0s 72us/sample - loss: 0.0523 - acc: 0.9800
Epoch 478/1000
150/150 [==============================] - 0s 68us/sample - loss: 0.0554 - acc: 0.9733
Epoch 479/1000
150/150 [==============================] - ETA: 0s - loss: 0.0846 - acc: 0.968 - 0s 90us/sample - loss: 0.0633 - acc: 0.9733
Epoch 480/1000
150/150 [==============================] - 0s 92us/sample - loss: 0.0644 - acc: 0.9733
Epoch 481/1000
150/150 [==============================] - 0s 86us/sample - loss: 0.0606 - acc: 0.9667
Epoch 482/1000
150/150 [==============================] - 0s 79us/sample - loss: 0.0662 - acc: 0.9733
Epoch 483/1000
150/150 [==============================] - 0s 89us/sample - loss: 0.0569 - acc: 0.9800
Epoch 484/1000
150/150 [==============================] - 0s 101us/sample - loss: 0.0475 - acc: 0.9867
Epoch 485/1000
150/150 [==============================] - 0s 85us/sample - loss: 0.0525 - acc: 0.9800
Epoch 486/1000
150/150 [==============================] - 

150/150 [==============================] - 0s 80us/sample - loss: 0.0520 - acc: 0.9733
Epoch 557/1000
150/150 [==============================] - 0s 85us/sample - loss: 0.0453 - acc: 0.9800
Epoch 558/1000
150/150 [==============================] - 0s 72us/sample - loss: 0.0557 - acc: 0.9867
Epoch 559/1000
150/150 [==============================] - 0s 82us/sample - loss: 0.0463 - acc: 0.9733
Epoch 560/1000
150/150 [==============================] - 0s 76us/sample - loss: 0.0607 - acc: 0.9733
Epoch 561/1000
150/150 [==============================] - 0s 94us/sample - loss: 0.0484 - acc: 0.9867
Epoch 562/1000
150/150 [==============================] - 0s 99us/sample - loss: 0.0530 - acc: 0.9800
Epoch 563/1000
150/150 [==============================] - 0s 84us/sample - loss: 0.0552 - acc: 0.9867
Epoch 564/1000
150/150 [==============================] - 0s 81us/sample - loss: 0.0607 - acc: 0.9733
Epoch 565/1000
150/150 [==============================] - 0s 88us/sample - loss: 0.0445 - acc: 0.

150/150 [==============================] - 0s 65us/sample - loss: 0.0434 - acc: 0.9867
Epoch 637/1000
150/150 [==============================] - 0s 103us/sample - loss: 0.0489 - acc: 0.9733
Epoch 638/1000
150/150 [==============================] - 0s 79us/sample - loss: 0.0466 - acc: 0.9800
Epoch 639/1000
150/150 [==============================] - 0s 78us/sample - loss: 0.0562 - acc: 0.9800
Epoch 640/1000
150/150 [==============================] - 0s 61us/sample - loss: 0.0505 - acc: 0.9733
Epoch 641/1000
150/150 [==============================] - 0s 80us/sample - loss: 0.0531 - acc: 0.9800
Epoch 642/1000
150/150 [==============================] - 0s 88us/sample - loss: 0.0626 - acc: 0.9667
Epoch 643/1000
150/150 [==============================] - 0s 85us/sample - loss: 0.0764 - acc: 0.9733
Epoch 644/1000
150/150 [==============================] - 0s 75us/sample - loss: 0.0684 - acc: 0.9800
Epoch 645/1000
150/150 [==============================] - 0s 83us/sample - loss: 0.0422 - acc: 0

150/150 [==============================] - 0s 84us/sample - loss: 0.0692 - acc: 0.9600
Epoch 717/1000
150/150 [==============================] - 0s 105us/sample - loss: 0.0631 - acc: 0.9733
Epoch 718/1000
150/150 [==============================] - 0s 88us/sample - loss: 0.0649 - acc: 0.9733
Epoch 719/1000
150/150 [==============================] - 0s 76us/sample - loss: 0.0948 - acc: 0.9533
Epoch 720/1000
150/150 [==============================] - 0s 90us/sample - loss: 0.0570 - acc: 0.9800
Epoch 721/1000
150/150 [==============================] - 0s 105us/sample - loss: 0.0832 - acc: 0.9533
Epoch 722/1000
150/150 [==============================] - 0s 116us/sample - loss: 0.0506 - acc: 0.9800
Epoch 723/1000
150/150 [==============================] - 0s 86us/sample - loss: 0.0445 - acc: 0.9867
Epoch 724/1000
150/150 [==============================] - 0s 91us/sample - loss: 0.0522 - acc: 0.9800
Epoch 725/1000
150/150 [==============================] - 0s 96us/sample - loss: 0.0419 - acc:

150/150 [==============================] - 0s 80us/sample - loss: 0.0457 - acc: 0.9800
Epoch 797/1000
150/150 [==============================] - 0s 77us/sample - loss: 0.0477 - acc: 0.9867
Epoch 798/1000
150/150 [==============================] - 0s 108us/sample - loss: 0.0553 - acc: 0.9733
Epoch 799/1000
150/150 [==============================] - 0s 113us/sample - loss: 0.0589 - acc: 0.9733
Epoch 800/1000
150/150 [==============================] - 0s 66us/sample - loss: 0.0651 - acc: 0.9800
Epoch 801/1000
150/150 [==============================] - 0s 64us/sample - loss: 0.0518 - acc: 0.9733
Epoch 802/1000
150/150 [==============================] - 0s 73us/sample - loss: 0.0500 - acc: 0.9867
Epoch 803/1000
150/150 [==============================] - 0s 78us/sample - loss: 0.0676 - acc: 0.9733
Epoch 804/1000
150/150 [==============================] - 0s 78us/sample - loss: 0.0662 - acc: 0.9600
Epoch 805/1000
150/150 [==============================] - 0s 78us/sample - loss: 0.0496 - acc: 

150/150 [==============================] - 0s 114us/sample - loss: 0.0492 - acc: 0.9800
Epoch 876/1000
150/150 [==============================] - 0s 82us/sample - loss: 0.0445 - acc: 0.9800
Epoch 877/1000
150/150 [==============================] - 0s 107us/sample - loss: 0.0476 - acc: 0.9800
Epoch 878/1000
150/150 [==============================] - 0s 112us/sample - loss: 0.0442 - acc: 0.9800
Epoch 879/1000
150/150 [==============================] - 0s 132us/sample - loss: 0.0451 - acc: 0.9867
Epoch 880/1000
150/150 [==============================] - 0s 80us/sample - loss: 0.0492 - acc: 0.9800
Epoch 881/1000
150/150 [==============================] - 0s 58us/sample - loss: 0.0547 - acc: 0.9733
Epoch 882/1000
150/150 [==============================] - 0s 81us/sample - loss: 0.0591 - acc: 0.9667
Epoch 883/1000
150/150 [==============================] - 0s 107us/sample - loss: 0.0448 - acc: 0.9867
Epoch 884/1000
150/150 [==============================] - 0s 86us/sample - loss: 0.0448 - ac

150/150 [==============================] - 0s 86us/sample - loss: 0.0553 - acc: 0.9733
Epoch 956/1000
150/150 [==============================] - 0s 80us/sample - loss: 0.0481 - acc: 0.9867
Epoch 957/1000
150/150 [==============================] - 0s 107us/sample - loss: 0.0528 - acc: 0.9733
Epoch 958/1000
150/150 [==============================] - 0s 106us/sample - loss: 0.0462 - acc: 0.9867
Epoch 959/1000
150/150 [==============================] - 0s 122us/sample - loss: 0.0516 - acc: 0.9733
Epoch 960/1000
150/150 [==============================] - 0s 107us/sample - loss: 0.0717 - acc: 0.9800
Epoch 961/1000
150/150 [==============================] - 0s 110us/sample - loss: 0.0345 - acc: 0.9867
Epoch 962/1000
150/150 [==============================] - 0s 80us/sample - loss: 0.0621 - acc: 0.9733
Epoch 963/1000
150/150 [==============================] - 0s 80us/sample - loss: 0.0638 - acc: 0.9867
Epoch 964/1000
150/150 [==============================] - 0s 82us/sample - loss: 0.0467 - ac

In [5]:
IO.get_weights() #W=(4,3), B=3개

[array([[ 2.180701 ,  0.7208689, -2.4003704],
        [ 6.9018393,  1.4064556, -3.9720879],
        [-6.6697927, -1.5545895,  6.000207 ],
        [-9.686211 , -4.2969127,  9.171561 ]], dtype=float32),
 array([  5.2275376,  11.207247 , -13.770847 ], dtype=float32)]

In [6]:
model.predict_classes(xdata)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [7]:
model.predict( np.array( [[5.1,3.5,1.4,0.2]] ) ) #여기에 예측하고 싶은 값 넣어주는 것이다. #결과값은 hx이다. 

array([[9.9999607e-01, 3.8782186e-06, 2.6017157e-26]], dtype=float32)

In [8]:
h.history['acc'][-1] #맨 마지막 인덱스를 참고하면 된다. 

0.9866667

In [10]:
h = model.predict(xdata)
h.argmax(axis=1)==(iris['target']).mean()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,