In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.optimizers import Adam
from sklearn import datasets
from tensorflow.keras.backend import one_hot
import matplotlib.pyplot as plt

In [2]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
sess = tf.Session()

In [5]:
t= one_hot(iris['target'],3)
sess.run(t)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [6]:
arr = iris['data'] #sl 5.1, sw 3.5, pl 1.4, pw 0.2 종분류 및 정확도
arr

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
xdata = arr
ydata = t

In [8]:
x = tf.placeholder(tf.float32,[None,4])
y = ydata

w = tf.Variable(tf.random_uniform([4,3]))
b = tf.Variable(tf.random_uniform([3]))

z = tf.matmul(x,w) + b
hx = tf.nn.softmax(z)
cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits= z, labels=y) #logits 인자에는 hx함수 , labels= Tensor형 yvalue
cost = tf.reduce_mean(cost_i)

optimizer = tf.train.GradientDescentOptimizer(0.1) #learning rate
train = optimizer.minimize(cost)
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [9]:
hist_loss =[]
patience = 16
min_delta = 0.001 
pcnt = 0

In [10]:
for i in range(30000):
    sess.run(train,{x:xdata}) #벼림 연산 # w = w.assign(w-0.1*g)
    c = sess.run(cost,{x:xdata}) 
    hist_loss.append( c )
    print(i, c)
    if i > 0 :
        if hist_loss[i-1]-hist_loss[i] > min_delta:
            pcnt = 0
        else:
            pcnt+= 1
        if pcnt > patience:
            print ('early stopping...')
            break

0 1.0859042
1 1.0146596
2 0.95516604
3 0.90558636
4 0.8641563
5 0.83037925
6 0.80411
7 0.78660095
8 0.7807518
9 0.78923994
10 0.8095653
11 0.83960557
12 0.8442818
13 0.860919
14 0.82852644
15 0.8434618
16 0.8014913
17 0.82459235
18 0.7780753
19 0.8081371
20 0.7577116
21 0.79324126
22 0.7396975
23 0.77959377
24 0.7235892
25 0.7669825
26 0.709036
27 0.7552302
28 0.6957655
29 0.74419713
30 0.6835621
31 0.7337699
32 0.6722551
33 0.72385573
34 0.6617067
35 0.7143796
36 0.6518064
37 0.70527977
38 0.64246285
39 0.6965037
40 0.63360125
41 0.68800855
42 0.62515914
43 0.6797581
44 0.61708343
45 0.6717204
46 0.60933065
47 0.6638708
48 0.6018626
49 0.65618587
50 0.594647
51 0.6486459
52 0.5876559
53 0.6412348
54 0.5808654
55 0.6339379
56 0.5742547
57 0.6267432
58 0.56780535
59 0.6196386
60 0.56150085
61 0.6126156
62 0.5553275
63 0.6056652
64 0.54927236
65 0.5987805
66 0.54332507
67 0.5919557
68 0.5374747
69 0.58518445
70 0.53171307
71 0.5784619
72 0.52603143
73 0.57178366
74 0.5204237
75 0.5651468

# 확률값

In [11]:
h = sess.run(hx,{x:[[5.1,3.5,1.4,0.2]]})
h

array([[9.5955694e-01, 4.0360402e-02, 8.2738217e-05]], dtype=float32)

# 종분류

In [12]:
feature_name = ['setosa','versicolor','virginica']
feature_name[int(h.argmax(axis = 1))]

'setosa'

# 정확도

In [13]:
predict = tf.cast( hx>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean( tf.cast(tf.equal(predict,y), dtype=tf.float32) )

In [14]:
sess.run(accuracy,{x:xdata})

0.98